name: Build/Publish Docker Image 

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros-distro: foxy
            platforms: "linux/amd64, linux/arm64"
          - ros-distro: galactic
            platforms: "linux/amd64, linux/arm64"
          - ros-distro: humble
            platforms: "linux/amd64, linux/arm64"

    steps:

    - name: Print branch name
      run: echo ${{ github.ref_name}}

    - name: Set SHORT_DATE env
      run: echo "SHORT_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Set IMAGE_NAME env
      run: |
        echo "repository name is: ${{ github.event.repository.name }}"
        echo "IMAGE_NAME=$(echo "${{ github.event.repository.name }}" | sed -r 's/([0-9a-zA-Z]+)-docker/\1/g')" >> $GITHUB_ENV

    - name: Print envs
      run: |
        echo "IMAGE_NAME=${{ env.IMAGE_NAME }}"
        echo "SHORT_DATE=${{ env.SHORT_DATE }}"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Just build (main branch)
      if: github.ref_name == 'main' && github.event_name == 'workflow_dispatch'
      uses: docker/build-push-action@v3
      with:
        platforms: ${{ matrix.platforms }}
        load: true # shorthand for --output=type=docker
        build-args: |
          ROS_DISTRO=${{ matrix.ros-distro }}
        tags: husarion/${{ env.IMAGE_NAME }}:${{ matrix.ros-distro }}-nightly

    - name: List docker images
      run: docker image ls

    - name: Set VERSION env
      run: echo "VERSION=$(docker run --rm -it husarion/${{ env.IMAGE_NAME }}:${{ matrix.ros-distro }}-nightly bash -c "cat /version.txt")" >> $GITHUB_ENV

    - name: Build and push with known version (main branch)
      if: github.ref_name == 'main' && github.event_name == 'workflow_dispatch'
      uses: docker/build-push-action@v3
      with:
        platforms: ${{ matrix.platforms }}
        push: true
        build-args: |
          ROS_DISTRO=${{ matrix.ros-distro }}
        tags: |
          husarion/${{ env.IMAGE_NAME }}:${{ matrix.ros-distro }}-nightly
          husarion/${{ env.IMAGE_NAME }}:${{ matrix.ros-distro }}-${{ env.VERSION }}-${{ env.SHORT_DATE }}

    - name: Build and push (feature branch)
      if: github.ref_name != 'main' && github.event_name == 'workflow_dispatch'
      uses: docker/build-push-action@v3
      with:
        platforms: ${{ matrix.platforms }}
        push: true
        build-args: |
          ROS_DISTRO=${{ matrix.ros-distro }}
        tags: husarion/${{ env.IMAGE_NAME }}:${{ matrix.ros-distro }}-${{ github.head_ref || github.ref_name }}
