name: Build/Publish Docker Image 

on: 
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - platforms: "linux/amd64"

    steps:

    - name: Print event name
      run: echo "Event name ${{ github.event_name }}"

    - name: Print branch name
      run: echo ${{ github.ref_name}}

    - name: Set SHORT_DATE env
      run: echo "SHORT_DATE=$(date +%y-%m-%d)" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push 
      uses: docker/build-push-action@v3
      with:
        platforms: ${{ matrix.platforms }}
        push: true
        tags: husarion/navigation2:humble-test
        no-cache: true


